// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20260304173046_up = [
  InsertTable('Adjunto'),
  InsertTable('ChatMensaje'),
  InsertTable('ChatterMensaje'),
  InsertTable('ComConversacion'),
  InsertTable('ComMensaje'),
  InsertTable('Rol'),
  InsertColumn('id', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('entidad_tipo', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('entidad_id', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('nombre', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('nombre_original', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('mime_type', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('tamanio_bytes', Column.integer, onTable: 'Adjunto'),
  InsertColumn('storage_path', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('storage_bucket', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('descripcion', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('es_publico', Column.boolean, onTable: 'Adjunto'),
  InsertColumn('created_at', Column.datetime, onTable: 'Adjunto'),
  InsertColumn('version', Column.integer, onTable: 'Adjunto'),
  InsertColumn('tags', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('icon_category', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('tamanio_label', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('extension', Column.varchar, onTable: 'Adjunto'),
  InsertColumn('id', Column.varchar, onTable: 'ChatMensaje'),
  InsertColumn('canal_id', Column.varchar, onTable: 'ChatMensaje'),
  InsertColumn('usuario_id', Column.varchar, onTable: 'ChatMensaje'),
  InsertColumn('cuerpo', Column.varchar, onTable: 'ChatMensaje'),
  InsertColumn('created_at', Column.datetime, onTable: 'ChatMensaje'),
  InsertColumn('version', Column.integer, onTable: 'ChatMensaje'),
  InsertColumn('id', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('entidad_tipo', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('entidad_id', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('tipo', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('subtype', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('es_interno', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('cuerpo', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('autor_id', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('autor_nombre', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('autor_avatar', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('creado_en', Column.datetime, onTable: 'ChatterMensaje'),
  InsertColumn('version', Column.integer, onTable: 'ChatterMensaje'),
  InsertColumn('adjuntos_ids', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('metadatos', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('es_log', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('es_comentario', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('es_email', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('es_actividad', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('es_nota_interna', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('tiene_adjuntos', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('tiene_campos_trackeados', Column.boolean, onTable: 'ChatterMensaje'),
  InsertColumn('autor_inicial', Column.varchar, onTable: 'ChatterMensaje'),
  InsertColumn('id', Column.varchar, onTable: 'ComConversacion'),
  InsertColumn('cuenta_id', Column.varchar, onTable: 'ComConversacion'),
  InsertColumn('canal', Column.varchar, onTable: 'ComConversacion'),
  InsertColumn('destinatario_ref', Column.varchar, onTable: 'ComConversacion'),
  InsertColumn('destinatario_nombre', Column.varchar, onTable: 'ComConversacion'),
  InsertColumn('ultimo_mensaje_en', Column.datetime, onTable: 'ComConversacion'),
  InsertColumn('valida_hasta', Column.datetime, onTable: 'ComConversacion'),
  InsertColumn('activa', Column.boolean, onTable: 'ComConversacion'),
  InsertColumn('creado_en', Column.datetime, onTable: 'ComConversacion'),
  InsertColumn('version', Column.integer, onTable: 'ComConversacion'),
  InsertColumn('ventana_wa_activa', Column.boolean, onTable: 'ComConversacion'),
  InsertColumn('display_name', Column.varchar, onTable: 'ComConversacion'),
  InsertColumn('meta_parsed', Column.varchar, onTable: 'ComConversacion'),
  InsertColumn('id', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('cuenta_id', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('conversacion_id', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('tipo', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('canal', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('destinatario_ref', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('destinatario_nombre', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('asunto', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('cuerpo', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('estado', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('mensaje_uid', Column.varchar, onTable: 'ComMensaje'),
  InsertColumn('enviado_en', Column.datetime, onTable: 'ComMensaje'),
  InsertColumn('entregado_en', Column.datetime, onTable: 'ComMensaje'),
  InsertColumn('leido_en', Column.datetime, onTable: 'ComMensaje'),
  InsertColumn('creado_en', Column.datetime, onTable: 'ComMensaje'),
  InsertColumn('version', Column.integer, onTable: 'ComMensaje'),
  InsertColumn('es_inbound', Column.boolean, onTable: 'ComMensaje'),
  InsertColumn('es_outbound', Column.boolean, onTable: 'ComMensaje'),
  InsertColumn('es_fallido', Column.boolean, onTable: 'ComMensaje'),
  InsertColumn('tiene_media', Column.boolean, onTable: 'ComMensaje'),
  InsertColumn('id', Column.varchar, onTable: 'Rol'),
  InsertColumn('codigo', Column.varchar, onTable: 'Rol'),
  InsertColumn('nombre', Column.varchar, onTable: 'Rol'),
  InsertColumn('descripcion', Column.varchar, onTable: 'Rol'),
  InsertColumn('es_sistema', Column.boolean, onTable: 'Rol'),
  InsertColumn('activo', Column.boolean, onTable: 'Rol'),
  InsertColumn('version', Column.integer, onTable: 'Rol'),
  CreateIndex(columns: ['entidad_tipo'], onTable: 'Adjunto', unique: false),
  CreateIndex(columns: ['entidad_id'], onTable: 'Adjunto', unique: false),
  CreateIndex(columns: ['empresa_id'], onTable: 'AlertaEmpresa', unique: false),
  CreateIndex(columns: ['estado'], onTable: 'AlertaEmpresa', unique: false),
  CreateIndex(columns: ['canal_id'], onTable: 'ChatMensaje', unique: false),
  CreateIndex(columns: ['entidad_tipo'], onTable: 'ChatterMensaje', unique: false),
  CreateIndex(columns: ['entidad_id'], onTable: 'ChatterMensaje', unique: false),
  CreateIndex(columns: ['activa'], onTable: 'ComConversacion', unique: false),
  CreateIndex(columns: ['conversacion_id'], onTable: 'ComMensaje', unique: false),
  CreateIndex(columns: ['estado'], onTable: 'ComMensaje', unique: false),
  CreateIndex(columns: ['activo'], onTable: 'Contacto', unique: false),
  CreateIndex(columns: ['empresa_id'], onTable: 'ModuloEmpresa', unique: false),
  CreateIndex(columns: ['empresa_id'], onTable: 'Notificacion', unique: false),
  CreateIndex(columns: ['leida'], onTable: 'Notificacion', unique: false),
  CreateIndex(columns: ['activo'], onTable: 'Producto', unique: false),
  CreateIndex(columns: ['empresa_id'], onTable: 'UsuarioEmpresaPerfil', unique: false)
];

const List<MigrationCommand> _migration_20260304173046_down = [
  DropTable('Adjunto'),
  DropTable('ChatMensaje'),
  DropTable('ChatterMensaje'),
  DropTable('ComConversacion'),
  DropTable('ComMensaje'),
  DropTable('Rol'),
  DropColumn('id', onTable: 'Adjunto'),
  DropColumn('entidad_tipo', onTable: 'Adjunto'),
  DropColumn('entidad_id', onTable: 'Adjunto'),
  DropColumn('nombre', onTable: 'Adjunto'),
  DropColumn('nombre_original', onTable: 'Adjunto'),
  DropColumn('mime_type', onTable: 'Adjunto'),
  DropColumn('tamanio_bytes', onTable: 'Adjunto'),
  DropColumn('storage_path', onTable: 'Adjunto'),
  DropColumn('storage_bucket', onTable: 'Adjunto'),
  DropColumn('descripcion', onTable: 'Adjunto'),
  DropColumn('es_publico', onTable: 'Adjunto'),
  DropColumn('created_at', onTable: 'Adjunto'),
  DropColumn('version', onTable: 'Adjunto'),
  DropColumn('tags', onTable: 'Adjunto'),
  DropColumn('icon_category', onTable: 'Adjunto'),
  DropColumn('tamanio_label', onTable: 'Adjunto'),
  DropColumn('extension', onTable: 'Adjunto'),
  DropColumn('id', onTable: 'ChatMensaje'),
  DropColumn('canal_id', onTable: 'ChatMensaje'),
  DropColumn('usuario_id', onTable: 'ChatMensaje'),
  DropColumn('cuerpo', onTable: 'ChatMensaje'),
  DropColumn('created_at', onTable: 'ChatMensaje'),
  DropColumn('version', onTable: 'ChatMensaje'),
  DropColumn('id', onTable: 'ChatterMensaje'),
  DropColumn('entidad_tipo', onTable: 'ChatterMensaje'),
  DropColumn('entidad_id', onTable: 'ChatterMensaje'),
  DropColumn('tipo', onTable: 'ChatterMensaje'),
  DropColumn('subtype', onTable: 'ChatterMensaje'),
  DropColumn('es_interno', onTable: 'ChatterMensaje'),
  DropColumn('cuerpo', onTable: 'ChatterMensaje'),
  DropColumn('autor_id', onTable: 'ChatterMensaje'),
  DropColumn('autor_nombre', onTable: 'ChatterMensaje'),
  DropColumn('autor_avatar', onTable: 'ChatterMensaje'),
  DropColumn('creado_en', onTable: 'ChatterMensaje'),
  DropColumn('version', onTable: 'ChatterMensaje'),
  DropColumn('adjuntos_ids', onTable: 'ChatterMensaje'),
  DropColumn('metadatos', onTable: 'ChatterMensaje'),
  DropColumn('es_log', onTable: 'ChatterMensaje'),
  DropColumn('es_comentario', onTable: 'ChatterMensaje'),
  DropColumn('es_email', onTable: 'ChatterMensaje'),
  DropColumn('es_actividad', onTable: 'ChatterMensaje'),
  DropColumn('es_nota_interna', onTable: 'ChatterMensaje'),
  DropColumn('tiene_adjuntos', onTable: 'ChatterMensaje'),
  DropColumn('tiene_campos_trackeados', onTable: 'ChatterMensaje'),
  DropColumn('autor_inicial', onTable: 'ChatterMensaje'),
  DropColumn('id', onTable: 'ComConversacion'),
  DropColumn('cuenta_id', onTable: 'ComConversacion'),
  DropColumn('canal', onTable: 'ComConversacion'),
  DropColumn('destinatario_ref', onTable: 'ComConversacion'),
  DropColumn('destinatario_nombre', onTable: 'ComConversacion'),
  DropColumn('ultimo_mensaje_en', onTable: 'ComConversacion'),
  DropColumn('valida_hasta', onTable: 'ComConversacion'),
  DropColumn('activa', onTable: 'ComConversacion'),
  DropColumn('creado_en', onTable: 'ComConversacion'),
  DropColumn('version', onTable: 'ComConversacion'),
  DropColumn('ventana_wa_activa', onTable: 'ComConversacion'),
  DropColumn('display_name', onTable: 'ComConversacion'),
  DropColumn('meta_parsed', onTable: 'ComConversacion'),
  DropColumn('id', onTable: 'ComMensaje'),
  DropColumn('cuenta_id', onTable: 'ComMensaje'),
  DropColumn('conversacion_id', onTable: 'ComMensaje'),
  DropColumn('tipo', onTable: 'ComMensaje'),
  DropColumn('canal', onTable: 'ComMensaje'),
  DropColumn('destinatario_ref', onTable: 'ComMensaje'),
  DropColumn('destinatario_nombre', onTable: 'ComMensaje'),
  DropColumn('asunto', onTable: 'ComMensaje'),
  DropColumn('cuerpo', onTable: 'ComMensaje'),
  DropColumn('estado', onTable: 'ComMensaje'),
  DropColumn('mensaje_uid', onTable: 'ComMensaje'),
  DropColumn('enviado_en', onTable: 'ComMensaje'),
  DropColumn('entregado_en', onTable: 'ComMensaje'),
  DropColumn('leido_en', onTable: 'ComMensaje'),
  DropColumn('creado_en', onTable: 'ComMensaje'),
  DropColumn('version', onTable: 'ComMensaje'),
  DropColumn('es_inbound', onTable: 'ComMensaje'),
  DropColumn('es_outbound', onTable: 'ComMensaje'),
  DropColumn('es_fallido', onTable: 'ComMensaje'),
  DropColumn('tiene_media', onTable: 'ComMensaje'),
  DropColumn('id', onTable: 'Rol'),
  DropColumn('codigo', onTable: 'Rol'),
  DropColumn('nombre', onTable: 'Rol'),
  DropColumn('descripcion', onTable: 'Rol'),
  DropColumn('es_sistema', onTable: 'Rol'),
  DropColumn('activo', onTable: 'Rol'),
  DropColumn('version', onTable: 'Rol'),
  DropIndex('index_Adjunto_on_entidad_tipo'),
  DropIndex('index_Adjunto_on_entidad_id'),
  DropIndex('index_AlertaEmpresa_on_empresa_id'),
  DropIndex('index_AlertaEmpresa_on_estado'),
  DropIndex('index_ChatMensaje_on_canal_id'),
  DropIndex('index_ChatterMensaje_on_entidad_tipo'),
  DropIndex('index_ChatterMensaje_on_entidad_id'),
  DropIndex('index_ComConversacion_on_activa'),
  DropIndex('index_ComMensaje_on_conversacion_id'),
  DropIndex('index_ComMensaje_on_estado'),
  DropIndex('index_Contacto_on_activo'),
  DropIndex('index_ModuloEmpresa_on_empresa_id'),
  DropIndex('index_Notificacion_on_empresa_id'),
  DropIndex('index_Notificacion_on_leida'),
  DropIndex('index_Producto_on_activo'),
  DropIndex('index_UsuarioEmpresaPerfil_on_empresa_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20260304173046',
  up: _migration_20260304173046_up,
  down: _migration_20260304173046_down,
)
class Migration20260304173046 extends Migration {
  const Migration20260304173046()
    : super(
        version: 20260304173046,
        up: _migration_20260304173046_up,
        down: _migration_20260304173046_down,
      );
}
